// <auto-generated />
using System;
using MVC0619Final_tempera.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC0619Final_tempera.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC0619Final_tempera.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<string>("ProductCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductCompany")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ProductDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProductPrice")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.ToTable("ProductTable", (string)null);

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            ProductCategory = "電子產品",
                            ProductCompany = "ABC 電子",
                            ProductDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "筆記型電腦",
                            ProductPrice = 25000
                        },
                        new
                        {
                            ProductID = 2,
                            ProductCategory = "電腦周邊",
                            ProductCompany = "XYZ 科技",
                            ProductDate = new DateTime(2023, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "無線滑鼠",
                            ProductPrice = 800
                        },
                        new
                        {
                            ProductID = 3,
                            ProductCategory = "電腦周邊",
                            ProductCompany = "Gaming Gear",
                            ProductDate = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "機械鍵盤",
                            ProductPrice = 3500
                        },
                        new
                        {
                            ProductID = 4,
                            ProductCategory = "電子產品",
                            ProductCompany = "Global Mobile",
                            ProductDate = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "智慧型手機",
                            ProductPrice = 18000
                        },
                        new
                        {
                            ProductID = 5,
                            ProductCategory = "音訊設備",
                            ProductCompany = "SoundWave",
                            ProductDate = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "藍牙耳機",
                            ProductPrice = 1200
                        },
                        new
                        {
                            ProductID = 6,
                            ProductCategory = "電子產品",
                            ProductCompany = "Visual Tech",
                            ProductDate = new DateTime(2023, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "LED 顯示器",
                            ProductPrice = 9900
                        },
                        new
                        {
                            ProductID = 7,
                            ProductCategory = "電腦周邊",
                            ProductCompany = "NetCam Pro",
                            ProductDate = new DateTime(2023, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "網路攝影機",
                            ProductPrice = 600
                        },
                        new
                        {
                            ProductID = 8,
                            ProductCategory = "電子配件",
                            ProductCompany = "PowerUp Inc.",
                            ProductDate = new DateTime(2023, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "行動電源",
                            ProductPrice = 750
                        },
                        new
                        {
                            ProductID = 9,
                            ProductCategory = "網路設備",
                            ProductCompany = "ConnectFast",
                            ProductDate = new DateTime(2023, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "路由器",
                            ProductPrice = 2000
                        },
                        new
                        {
                            ProductID = 10,
                            ProductCategory = "穿戴裝置",
                            ProductCompany = "Wearable Innovations",
                            ProductDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "智慧手錶",
                            ProductPrice = 5000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
